---
title: "Quarto Paths"
author:
  - name: "Álex Espinosa Correa"
    affiliation: "Universidad de Antioquia"
date: "2024-11-02"
lang: es
execute:
  echo: true
format:
  html:
    embed-resources: true
---

Ahora intenta importar los datos por los métodos demostrados en el script `01_script_rutas.R`.

Modifique el código según sea necesario.

```{r}
#| label: rutas-absolutas

# 1 Rutas absolutas ----

datos_1 <-
  read.csv(
    "C:/Users/alex/Documents/r/etnobotanica-workshop/reproducibilidad/ejercicio/data/raw_data.csv"
  )

head(datos_1)
```

```{r}
#| label: rutas-relativas

# 2 Rutas relativas (directorio de trabajo) ----
# (No use el package `here`)
datos_2 <-
  read.csv(
    "raw_data.csv"
  )

head(datos_2)
```


```{r}
#| label: rutas-relativas-here

# 3 Rutas relativas (directorio del proyecto) ----
# (Use el paquete `here`)

datos_3 <-
  read.csv(
    "raw_data.csv"
  )

head(datos_3 )
```

Renderizar este documento para confirmar que los datos han sido leídos.

Si sus rutas funcionan correctamente, el documento renderizado debería mostrar los seis primeros datos `raw_data.csv`.
